In [59]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.config import settings
from src.aggregations import territorial, person, labor,cadunico
import pandas as pd 
import numpy as np
from pathlib import Path
import importlib

importlib.reload(settings)
importlib.reload(territorial)
importlib.reload(person)
importlib.reload(labor)
importlib.reload(cadunico)



pd.set_option("display.max_columns", None)

In [81]:
df_cubo = pd.read_excel(settings.CUBO_PATH)

In [4]:
df_cubo_x = pd.read_excel(settings.DATA_PATH /'input_data' /'dados_cubo_final_v0__2026-05-28_16-48.xlsx')

In [ ]:
# Section 1
# bignumber1.csv

# Valor executado por estado x municipio abs / percentual 
df_cubo_est = df_cubo[df_cubo['tipo_ente'] == 'ESTADO']
df_cubo_mun = df_cubo[df_cubo['tipo_ente'] == 'MUNICIPIO']

# Totais executados com ceil
valor_estados = np.ceil(df_cubo_est["valor_transacao"].sum())
valor_municipios = np.ceil(df_cubo_mun["valor_transacao"].sum())

# Valores de referência
total_estados = 1_510_000_000
total_municipios = 1_490_000_000

df_execucao = pd.DataFrame({
    "Estados_DF": [valor_estados],
    "Municipios_DF": [valor_municipios],
    "perc_executado_estados": [valor_estados / total_estados],
    "perc_executado_municipios": [valor_municipios / total_municipios],
})

df_execucao

,Estados_DF,Municipios_DF,perc_executado_estados,perc_executado_municipios
0,1.450514e+09,1.395481e+09,0.960606,0.936565

In [42]:
df_execucao.to_csv('s1_bn1.csv')

In [35]:
# executed_value_by.csv
df_states       = territorial.executed_value_n_contemplados_qty_by(df_cubo=df_cubo_x, by_filter='ESTADO')
df_municipality = territorial.executed_value_n_contemplados_qty_by(df_cubo=df_cubo_x, by_filter='MUNICIPIO')
df_uf           = territorial.executed_value_n_contemplados_qty_by(df_cubo=df_cubo_x, by_filter='UF')

df_states.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_state.csv')
df_municipality.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_municipality.csv')
df_uf.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_uf.csv')

In [25]:
df_uf_new = territorial.aggregate_faixa_valor_ju_wide_by_uf(df_cubo=df_cubo_x)
df_uf_new.to_csv(settings.DATA_PATH_SECTION2 / 'aggregate_faixa_valor_ju_wide_by_uf.csv')

In [31]:
df_uf_new = territorial.aggregate_faixa_valor_ju_wide_by_uf(df_cubo=df_cubo_x, by_filter='ESTADO')
df_uf_new.to_csv(settings.DATA_PATH_SECTION2 / 'aggregate_faixa_valor_ju_wide_by_state.csv')

In [32]:
df_uf_new

,uf,total_contemplados_uf,valor_total_uf,qtd_ate_2_mil,perc_qtd_ate_2_mil,valor_ate_2_mil,perc_valor_ate_2_mil,qtd_de_2_a_10_mil,perc_qtd_de_2_a_10_mil,valor_de_2_a_10_mil,perc_valor_de_2_a_10_mil,qtd_de_10_a_50_mil,perc_qtd_de_10_a_50_mil,valor_de_10_a_50_mil,perc_valor_de_10_a_50_mil,qtd_de_50_a_200_mil,perc_qtd_de_50_a_200_mil,valor_de_50_a_200_mil,perc_valor_de_50_a_200_mil,qtd_acima_de_200_mil,perc_qtd_acima_de_200_mil,valor_acima_de_200_mil,perc_valor_acima_de_200_mil
0,AC,452,17743059.01,13,0.028761,16003.85,0.000902,25,0.05531,158006.45,0.008905,368,0.814159,9145149.8,0.515421,36,0.079646,3264137.4,0.183967,10,0.022124,5159761.51,0.290805
1,AL,1269,35128148.39,0,0.0,0.0,0.0,455,0.35855,3308700.0,0.094189,704,0.554768,16799000.0,0.47822,98,0.077226,8734000.0,0.248633,12,0.009456,6286448.39,0.178958
2,AM,622,44222860.52,0,0.0,0.0,0.0,33,0.053055,150107.92,0.003394,376,0.604502,14015540.53,0.31693,196,0.315113,20524698.54,0.46412,17,0.027331,9532513.53,0.215556
3,AP,236,17120298.32,0,0.0,0.0,0.0,50,0.211864,500000.0,0.029205,143,0.605932,3410000.0,0.199179,23,0.097458,2262000.0,0.132124,20,0.084746,10948298.32,0.639492
4,BA,1188,76394220.84,0,0.0,0.0,0.0,199,0.167508,883183.76,0.011561,647,0.544613,24522451.78,0.320999,280,0.23569,29927505.98,0.391751,62,0.052189,21061079.32,0.275689
5,CE,913,78727917.79,0,0.0,0.0,0.0,78,0.085433,438847.82,0.005574,486,0.532311,16376475.31,0.208014,293,0.32092,33517373.94,0.425737,56,0.061336,28395220.72,0.360675
6,DF,76,21309243.88,0,0.0,0.0,0.0,0,0.0,0.0,0.0,11,0.144737,312575.09,0.014669,48,0.631579,4480003.53,0.210238,17,0.223684,16516665.26,0.775094
7,ES,495,29866850.17,0,0.0,0.0,0.0,167,0.337374,915779.97,0.030662,189,0.381818,6396789.91,0.214177,123,0.248485,12346885.65,0.413398,16,0.032323,10207394.64,0.341763
8,GO,471,55985604.87,0,0.0,0.0,0.0,12,0.025478,120000.0,0.002143,180,0.382166,7387900.0,0.131961,216,0.458599,24957200.0,0.445779,63,0.133758,23520504.87,0.420117
9,MA,790,63390851.19,0,0.0,0.0,0.0,81,0.102532,681008.49,0.010743,491,0.621519,13594167.87,0.21445,157,0.198734,16901053.74,0.266617,61,0.077215,32214621.09,0.50819
10,MG,3284,110795695.1,8,0.002436,11328.44,0.000102,247,0.075213,1861408.34,0.0168,2452,0.74665,55421787.9,0.500216,568,0.17296,48411981.9,0.436948,9,0.002741,5089188.52,0.045933
11,MS,520,23316653.57,1,0.001923,2000.0,0.000086,239,0.459615,1573456.1,0.067482,195,0.375,4966702.61,0.213011,66,0.126923,6635388.79,0.284577,19,0.036538,10139106.07,0.434844
12,MT,239,24571646.22,0,0.0,0.0,0.0,0,0.0,0.0,0.0,59,0.246862,2245000.0,0.091365,168,0.702929,14600479.56,0.5942,12,0.050209,7726166.66,0.314434
13,PA,573,73195925.77,0,0.0,0.0,0.0,0,0.0,0.0,0.0,478,0.834206,12521358.01,0.171066,88,0.153578,8324284.57,0.113726,7,0.012216,52350283.19,0.715208
14,PB,1755,37177439.73,45,0.025641,84100.0,0.002262,873,0.497436,5890727.61,0.158449,733,0.417664,19275674.5,0.518478,99,0.05641,8361879.0,0.224918,5,0.002849,3565058.62,0.095893
15,PE,2241,75277246.24,4,0.001785,6525.98,0.000087,681,0.303882,5610271.6,0.074528,1143,0.51004,31076909.7,0.412833,397,0.177153,30846321.9,0.40977,16,0.00714,7737217.06,0.102783
16,PI,629,31576333.77,0,0.0,0.0,0.0,293,0.465819,1980000.0,0.062705,163,0.259141,5750000.0,0.182098,167,0.265501,18300000.0,0.579548,6,0.009539,5546333.77,0.175648
17,PR,671,73147845.91,0,0.0,0.0,0.0,182,0.271237,1088850.95,0.014886,181,0.269747,7388895.62,0.101013,216,0.321908,30191958.72,0.412753,92,0.137109,34478140.62,0.471349
18,RJ,853,85881913.38,0,0.0,0.0,0.0,1,0.001172,8048.17,0.000094,432,0.506448,15647474.17,0.182198,372,0.436108,39609692.0,0.461211,48,0.056272,30616699.04,0.356498
19,RN,946,27951151.25,0,0.0,0.0,0.0,214,0.226216,1814374.99,0.064912,655,0.692389,16518124.15,0.590964,72,0.07611,5167242.06,0.184867,5,0.005285,4451410.05,0.159257
20,RO,31,466832.92,2,0.064516,3115.0,0.006673,15,0.483871,57812.5,0.12384,13,0.419355,280000.0,0.599786,1,0.032258,125905.42,0.269701,0,0.0,0.0,0.0
21,RR,480,14908203.2,1,0.002083,1000.0,0.000067,212,0.441667,1871050.0,0.125505,189,0.39375,3975176.6,0.266644,76,0.158333,7905514.16,0.530279,2,0.004167,1155462.44,0.077505
22,RS,620,70502784.62,13,0.020968,16802.8,0.000238,119,0.191935,315981.82,0.004482,0,0.0,0.0,0.0,443,0.714516,48920000.0,0.693873,45,0.072581,21250000.0,0.301407
23,SC,699,27961958.44,2,0.002861,3242.44,0.000116,6,0.008584,36711.34,0.001313,564,0.806867,13593352.58,0.486137,113,0.16166,9730612.08,0.347995,14,0.020029,4598040.0,0.164439
24,SE,301,22540730.32,0,0.0,0.0,0.0,75,0.249169,746000.0,0.033096,109,0.362126,3304441.14,0.146599,97,0.322259,9895357.91,0.438999,20,0.066445,8594931.27,0.381307
25,SP,1211,290180006.82,0,0.0,0.0,0.0,129,0.106524,1054877.49,0.003635,197,0.162675,4236662.37,0.0146,428,0.353427,58241851.33,0.200709,457,0.377374,226646615.63,0.781055
26,TO,485,21172903.86,0,0.0,0.0,0.0,93,0.191753,697500.0,0.032943,296,0.610309,8944450.0,0.422448,83,0.171134,7045953.86,0.332782,13,0.026804,4485000.0,0.211827

In [22]:
# executed_value_by_region
df_states_region       = territorial.aggregate_execution_by_region(df_cubo=df_cubo, by_filter='ESTADO')
df_municipality_region = territorial.aggregate_execution_by_region(df_cubo=df_cubo, by_filter='MUNICIPIO')
df_uf_region           = territorial.aggregate_execution_by_region(df_cubo=df_cubo, by_filter='UF')

df_states_region.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_region_state.csv')
df_municipality_region.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_region_municipality.csv')
df_uf_region.to_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_region_uf.csv')

In [25]:
# aggregate_values_by
df_municipality_agg     = territorial.aggregate_execution_summary_by_scope(df_cubo=df_cubo, scope='MUNICIPIO')
df_state_agg            = territorial.aggregate_execution_summary_by_scope(df_cubo=df_cubo, scope='ESTADO')
df_capital_agg          = territorial.aggregate_capital_interior_summary(df_cubo=df_cubo)

df_municipality_agg.to_csv(settings.DATA_PATH_SECTION1 / 'aggregate_values_by_municipality.csv')
df_capital_agg.to_csv(settings.DATA_PATH_SECTION1 / 'aggregate_values_by_capital.csv')
df_state_agg.to_csv(settings.DATA_PATH_SECTION1 / 'aggregate_values_by_state.csv')

In [83]:
# values_by_population_size
df_population_size = territorial.aggregate_execution_by_porte_with_estado(df_cubo=df_cubo)
denominador_urbano_rural = (
    df_population_size["valor_urbano_por_porte"]
    + df_population_size["valor_rural_por_porte"]
)

df_population_size["percentual_valor_urbano_por_porte"] = np.where(
    denominador_urbano_rural.ne(0),
    df_population_size["valor_urbano_por_porte"] / denominador_urbano_rural,
    np.nan
)

df_population_size["percentual_valor_rural_por_porte"] = np.where(
    denominador_urbano_rural.ne(0),
    df_population_size["valor_rural_por_porte"] / denominador_urbano_rural,
    np.nan
)
# df_population_size.to_csv(settings.DATA_PATH_SECTION1 / 'values_by_population_size.csv')

In [87]:
colunas = [
    "porte_populacional",
    "Até 2 mil",
    "2 a 10 mil",
    "10 a 50 mil",
    "50 a 200 mil",
    "200 a 500 mil",
    "500 mil a 1 milhão",
    "1 milhão a 10 milhões",
    "Acima de 10 milhões",
]

In [99]:
df_population_size_att = df_population_size[colunas]
df_population_size_att = df_population_size_att[df_population_size_att['porte_populacional'] != -99]

In [100]:
df_population_size_att

,porte_populacional,Até 2 mil,2 a 10 mil,10 a 50 mil,50 a 200 mil,200 a 500 mil,500 mil a 1 milhão,1 milhão a 10 milhões,Acima de 10 milhões
1,4_grande,2321,12986,13359,2388,162,22,17,0
2,1_pequeno_i,28695,23629,4511,447,7,0,0,0
3,2_pequeno_ii,14287,19876,4424,335,22,0,0,0
4,3_medio,3645,9523,3913,254,12,1,0,0

In [20]:
df_population_size.to_csv(settings.DATA_PATH_SECTION1 / 'values_by_population_size.csv')

In [ ]:
147500752.72/(147500752.72+12718073.4

0.920620605530623

In [4]:
df_population_size_mean = territorial.resumo_valor_por_porte_municipio(df_cubo=df_cubo)

In [6]:
df_population_size_mean.to_csv(settings.DATA_PATH_SECTION1 / 'population_size_mean.csv')

In [74]:
# values_by_special_territory
df_special_territory_municipality = territorial.aggregate_special_territories_by(
    df_cubo=df_cubo, 
    categories=settings.CATEGORIES_SPECIAL_TERRITORIES, 
    by_filter="MUNICIPIO"
)

df_special_territory_state = territorial.aggregate_special_territories_by(
    df_cubo=df_cubo, 
    categories=settings.CATEGORIES_SPECIAL_TERRITORIES, 
    by_filter="ESTADO"
)

df_special_territory_uf = territorial.aggregate_special_territories_by(
    df_cubo=df_cubo, 
    categories=settings.CATEGORIES_SPECIAL_TERRITORIES, 
    by_filter="UF"
)

df_special_territory_municipality.to_csv(settings.DATA_PATH_SECTION1 / 'values_by_special_territory_municipality.csv')
df_special_territory_state.to_csv(settings.DATA_PATH_SECTION1 / 'values_by_special_territory_state.csv')
df_special_territory_uf.to_csv(settings.DATA_PATH_SECTION1 / 'values_by_special_territory_uf.csv')

In [75]:
df_special_territory_uf

,cod_tipo_nome,valor_transacao,perc_valor_transacao,quantidade_contemplados,perc_quantidade_contemplados,qtd_tipo_documento_CNPJ,qtd_tipo_documento_CPF,valor_tipo_documento_CNPJ,valor_tipo_documento_CPF,min_valor_tipo_documento_CNPJ,min_valor_tipo_documento_CPF,mediana_valor_tipo_documento_CNPJ,mediana_valor_tipo_documento_CPF,max_valor_tipo_documento_CNPJ,max_valor_tipo_documento_CPF,media_valor_tipo_documento_CNPJ,media_valor_tipo_documento_CPF
1,Favela e Comunidade Urbana,138146185,0.0485,4555,0.0273,864,3691,76558971,61587214,431,400,36000,10000,22109765,400000,109214,16874
3,Agrupamento quilombola,7369210,0.0026,481,0.0029,72,409,3509108,3860103,1034,500,29307,3200,329600,150000,52375,9532
4,Agrupamento indígena,5078944,0.0018,254,0.0015,22,232,1391182,3687762,4000,500,25883,5500,250000,294095,63236,16175

In [66]:
df_cubo.head(2)

,ente,tipo_ente,tipo_documento,faixa_vlr_pago,uf,nome_ente,regiao,flag_capital,porte_populacional,Sexo,Estrangeiro,NomeNaturezaOcupacao,NomeOcupacaoPrincipal,faixa_etaria,flag_cpf_mei,cnaePrincipal,naturezaJuridica,porte,cnpj_optante_mei,raca_cor_desc_description,escolaridade_description,ind_deficiencia,tipo_deficiencia_description,tipo_vinculo_description,faixa_salarial_rais,CBO_2002_RAIS,cbo_codigo,cbo_descricao,SITUACAO,cod_situacao_nome,cod_tipo_nome,pessoaCad_cadunico,familiaPBF_cadunico,fxRendaFamiliarTotal_desc_cadunico,caracDomicilio_desc_cadunico,fxRendaPerCapita_desc_cadunico,pertence_bpc,categoria_municipio_ibge,faixa_vlr_pago_ju_bbagil,situacao_renda_cadunico,cod_cnae_principal_receita_cnpj,descr_cnae_principal_receita_cnpj,naturezajuridica_agrupada_receita_cnpj,flag_cnae_cultural,tipo_vinculo_agregado_rais,escolaridade_agregado_rais,flag_cbo_cultural_rais,flag_join_rais,quantidade,valor_transacao,min_valor_transacao,max_valor_transacao,sum_populacao
0,AC_Acre_12,ESTADO,CNPJ,1 milhão a 10 milhões,AC,Acre,Norte,False,-99,NaN,NaN,NaN,NaN,NaN,False,"{'codigo': '7820500', 'descricao': 'Locação de...","{'codigo': '2062', 'descricao': 'Sociedade Emp...",01 - MicroEmpresa-ME,0.0,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NaN,NaN,NaN,Urbana,Área urbana de alta densidade de edificações d...,Não especial,NaN,NaN,NaN,NaN,NaN,NaN,Interior,Acima de 200 mil,NaN,7820500.0,Locação de mão-de-obra temporária,Entidades empresariais | EPP | Microempresa,CNAE NAO CULTURAL,NaN,NaN,NaN,False,1,2034002.65,2034002.65,2034002.65,880631
1,AC_Acre_12,ESTADO,CNPJ,10 a 50 mil,AC,Acre,Norte,False,-99,NaN,NaN,NaN,NaN,NaN,False,"{'codigo': '1629301', 'descricao': 'Fabricação...","{'codigo': '2135', 'descricao': 'Empresário (I...",01 - MicroEmpresa-ME,1.0,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NaN,NaN,NaN,Urbana,Área urbana de alta densidade de edificações d...,Não especial,NaN,NaN,NaN,NaN,NaN,NaN,Interior,De 10 a 50 mil,NaN,1629301.0,"Fabricação de artefatos diversos de madeira, e...",Entidades empresariais | EPP | Microempresa,CNAE CULTURAL,NaN,NaN,NaN,False,1,50000.00,50000.00,50000.00,880631

In [64]:
# special_territory_w_ibge_by_brazil
df_vis_territorio_brasil = territorial.generate_special_territories_brazil_view(df_cubo=df_cubo)
df_vis_territorio_brasil.to_csv(settings.DATA_PATH_SECTION1 / 'special_territory_w_ibge_by_brazil.csv')

In [52]:
# aggregate_by_local_residencia
df_interior_rm_uf = territorial.aggregate_by_local_residencia(df_cubo=df_cubo_x, visao='uf')
df_interior_rm_uf.to_csv(settings.DATA_PATH_SECTION1 / 'aggregate_by_local_residencia_uf.csv')

In [61]:
df_cubo.head(2)

,ente,tipo_ente,tipo_documento,faixa_vlr_pago,uf,nome_ente,regiao,flag_capital,porte_populacional,Sexo,Estrangeiro,NomeNaturezaOcupacao,NomeOcupacaoPrincipal,faixa_etaria,flag_cpf_mei,cnaePrincipal,naturezaJuridica,porte,cnpj_optante_mei,raca_cor_desc_description,escolaridade_description,ind_deficiencia,tipo_deficiencia_description,tipo_vinculo_description,faixa_salarial_rais,CBO_2002_RAIS,cbo_codigo,cbo_descricao,SITUACAO,cod_situacao_nome,cod_tipo_nome,pessoaCad_cadunico,familiaPBF_cadunico,fxRendaFamiliarTotal_desc_cadunico,caracDomicilio_desc_cadunico,fxRendaPerCapita_desc_cadunico,pertence_bpc,categoria_municipio_ibge,faixa_vlr_pago_ju_bbagil,situacao_renda_cadunico,cod_cnae_principal_receita_cnpj,descr_cnae_principal_receita_cnpj,naturezajuridica_agrupada_receita_cnpj,flag_cnae_cultural,tipo_vinculo_agregado_rais,escolaridade_agregado_rais,flag_cbo_cultural_rais,flag_join_rais,quantidade,valor_transacao,min_valor_transacao,max_valor_transacao,sum_populacao
0,AC_Acre_12,ESTADO,CNPJ,1 milhão a 10 milhões,AC,Acre,Norte,False,-99,NaN,NaN,NaN,NaN,NaN,False,"{'codigo': '7820500', 'descricao': 'Locação de...","{'codigo': '2062', 'descricao': 'Sociedade Emp...",01 - MicroEmpresa-ME,0.0,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NaN,NaN,NaN,Urbana,Área urbana de alta densidade de edificações d...,Não especial,NaN,NaN,NaN,NaN,NaN,NaN,Interior,Acima de 200 mil,NaN,7820500.0,Locação de mão-de-obra temporária,Entidades empresariais | EPP | Microempresa,CNAE NAO CULTURAL,NaN,NaN,NaN,False,1,2034002.65,2034002.65,2034002.65,880631
1,AC_Acre_12,ESTADO,CNPJ,10 a 50 mil,AC,Acre,Norte,False,-99,NaN,NaN,NaN,NaN,NaN,False,"{'codigo': '1629301', 'descricao': 'Fabricação...","{'codigo': '2135', 'descricao': 'Empresário (I...",01 - MicroEmpresa-ME,1.0,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NaN,NaN,NaN,Urbana,Área urbana de alta densidade de edificações d...,Não especial,NaN,NaN,NaN,NaN,NaN,NaN,Interior,De 10 a 50 mil,NaN,1629301.0,"Fabricação de artefatos diversos de madeira, e...",Entidades empresariais | EPP | Microempresa,CNAE CULTURAL,NaN,NaN,NaN,False,1,50000.00,50000.00,50000.00,880631

# Section 2

In [27]:
df_values_by_person_type_uf = territorial.aggregate_execution_by_person_type(df_cubo=df_cubo, by_filter='UF')
df_values_by_person_type_state = territorial.aggregate_execution_by_person_type(df_cubo=df_cubo, by_filter='ESTADO')
df_values_by_person_type_municipality = territorial.aggregate_execution_by_person_type(df_cubo=df_cubo, by_filter='MUNICIPIO')

df_values_by_person_type_uf.to_csv(settings.DATA_PATH_SECTION2 / 'aggregate_execution_by_person_type_uf.csv')
df_values_by_person_type_state.to_csv(settings.DATA_PATH_SECTION2 / 'aggregate_execution_by_person_type_state.csv')
df_values_by_person_type_municipality.to_csv(settings.DATA_PATH_SECTION2 / 'aggregate_execution_by_person_type_municipality.csv')

In [6]:
df_cubo_x['faixa_vlr_pago_ju_bbagil'].unique()

<ArrowStringArray>
['Acima de 200 mil',   'De 10 a 50 mil',  'De 50 a 200 mil',
    'De 2 a 10 mil',        'Até 2 mil']
Length: 5, dtype: str

In [ ]:
df_faixa_valor = territorial.aggregate_faixa_valor_ju_by(df_cubo=df_cubo_x)
# df_faixa_valor.to_csv(settings.DATA_PATH_SECTION2 / 'values_range_by_brazil_v2.csv')

In [36]:
df_faixa_valor

,faixa_vlr_pago_ju_bbagil,Quantidade de contemplados,Valor total,% de contemplados,% do valor total
0,Até 2 mil,89,144118.51,0.004036,0.000099
1,De 2 a 10 mil,4479,31762705.32,0.203129,0.021898
2,De 10 a 50 mil,11454,317106059.64,0.519456,0.218616
3,De 50 a 200 mil,4924,509229282.04,0.223311,0.351068
4,Acima de 200 mil,1104,592272160.59,0.050068,0.408319

In [30]:
df_faixa_valor = territorial.aggregate_faixa_valor_ju_by(df_cubo=df_cubo_x, by_filter='ESTADO')
df_faixa_valor.to_csv(settings.DATA_PATH_SECTION2 / 'values_range_by_state_v2.csv')

In [38]:
df_aux = pd.read_parquet(settings.DATA_PATH / 'input_data'/ 'non-public' / 'df_aux_cubo.parquet')

In [ ]:
df_box = territorial.make_boxplot_df_faixa_valor(df_aux=df_aux)

In [71]:
df_box_qtd_contemplados = df_box[df_box['metrica'] == 'quantidade_contemplados']
df_box_qtd_contemplados.to_csv(settings.DATA_PATH_SECTION2 / 'faixa_valor_box_plot_qtd_contemplados_state.csv')

In [78]:
import pandas as pd

# Filtra apenas ESTADO
df_estado = df_aux[df_aux["tipo_ente_bbagil"] == "ESTADO"].copy()

# Garante que a coluna de valor está numérica
df_estado["valor_transacao_total_bbagil"] = pd.to_numeric(
    df_estado["valor_transacao_total_bbagil"],
    errors="coerce"
)

# Remove valores nulos
serie_valor = df_estado["valor_transacao_total_bbagil"].dropna()

# Tabela geral de percentis e quartis
df_percentis_estado = pd.DataFrame({
    "tipo_ente": ["ESTADO"],
    "quantidade_contemplados": [serie_valor.count()],
    "valor_minimo": [serie_valor.min()],
    "p1": [serie_valor.quantile(0.01)],
    "q1": [serie_valor.quantile(0.25)],
    "q2_mediana": [serie_valor.quantile(0.50)],
    "q3": [serie_valor.quantile(0.75)],
    "p99": [serie_valor.quantile(0.99)],
    "valor_maximo": [serie_valor.max()],
    "media": [serie_valor.mean()],
    "desvio_padrao": [serie_valor.std()]
})

df_percentis_estado

,tipo_ente,quantidade_contemplados,valor_minimo,p1,q1,q2_mediana,q3,p99,valor_maximo,media,desvio_padrao
0,ESTADO,22050,429.37,2824.0,12500.0,30000.0,60000.0,500000.0,22109764.92,65782.962635,264704.278241

In [ ]:
    df_aux

,ente_bbagil,documento_beneficiario_bbagil,tipo_ente_bbagil,tipo_documento_bbagil,valor_transacao_total_bbagil,ano_mes_max_bbagil,ano_mes_min_bbagil,ano_max_bbagil,ano_min_bbagil,faixa_vlr_pago_bbagil,faixa_vlr_pago_ju_bbagil,uf_bbagil,cod_ibge_bbagil,nome_ente_bbagil,residenteexterior_receita_cpf,sexo_receita_cpf,estrangeiro_receita_cpf,nomenaturezaocupacao_receita_cpf,nomeocupacaoprincipal_receita_cpf,idade_receita_cpf,faixa_etaria_receita_cpf,codigomunicipio_receita_cpf,flag_join_receita_cpf,cnaeprincipal_receita_cnpj,cnaesecundarias_receita_cnpj,naturezajuridica_receita_cnpj,porte_receita_cnpj,cnpj_optante_mei_receita_cnpj,flag_cnae_cultural_receita_cnpj,codigo_municipio_receita_cnpj,cod_cnae_principal_receita_cnpj,descr_cnae_principal_receita_cnpj,naturezajuridica_agrupada_receita_cnpj,flag_cnae_educacao_receita_cnpj,flag_cnae_audiovisual_receita_cnpj,flag_join_receita_cnpj,raca_cor_desc_description_rais,escolaridade_description_rais,escolaridade_agregado_rais,indicador_portador_deficiencia_codigo_rais,tipo_deficiencia_description_rais,indicador_pcd_rais,tipo_vinculo_description_rais,tipo_vinculo_agregado_rais,cbo_2002_ocupacao_codigo_rais,vinculo_ativo_2024_rais,flag_cbo_cultural_rais,faixa_salarial_rais,flag_join_rais,cbo_codigo_rel_trabalhista_inss,cbo_descricao_rel_trabalhista_inss,flag_cbo_cultural_rel_trabalhista_inss,flag_join_trabalhista_inss,situacao_cnfe,cod_situacao_nome_cnefe,cod_tipo_nome_cnefe,flag_join_cnefe,pessoacadastrada_cadunico,familiabeneficiariapbf_cadunico,faixarendafamiliartotal_descricao_cadunico,caracteristicaslocaldomicilio_descricao_cadunico,faixarendafamiliarpercapita_descricao_cadunico,situacao_renda_cadunico,pertence_bpc,cod_ibge,populacao,flag_capital,porte_populacional,nome_macrorregiao,chave_metro,cod_ibge_metropol,flag_regiao_metropolitana,cod_ibge_capital,aux_flag_capital_estado,categoria_municipio_ibge,local_residencia_contemplados,flag_cpf_mei
0,AC_Acre_12,00028365216,ESTADO,CPF,80000.00,202503,202412,2025,2024,50 a 200 mil,De 50 a 200 mil,AC,12,Acre,N,Feminino,N,"Aposentado, militar reformado e pensionista de...",Outras ocupações não especificadas anteriormente,36.0,25-54 anos,1200807,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,411010,ASSISTENTE ADMINISTRATIVO,False,True,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,True,True,De 0 a um salário-mínimo,Urbanas,De 0 até R$ 109,Pobreza,False,1200807,880631.0,False,-99,Norte,1200807,NaN,False,NaN,False,Interior,Interior,False
1,AC_Acre_12,00028510240,ESTADO,CPF,15000.00,202502,202502,2025,2025,10 a 50 mil,De 10 a 50 mil,AC,12,Acre,N,Masculino,N,NaN,NaN,79.0,65+ anos,1200302,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,False,True,Rural,Área rural (exclusive aglomerados),Não especial,True,None,None,NaN,NaN,NaN,NaN,False,1200302,880631.0,False,-99,Norte,1200302,NaN,False,NaN,False,Interior,Interior,False
2,AC_Acre_12,00028539222,ESTADO,CPF,15000.00,202502,202502,2025,2025,10 a 50 mil,De 10 a 50 mil,AC,12,Acre,N,Masculino,N,NaN,NaN,78.0,65+ anos,1200302,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,False,True,Rural,Área rural (exclusive aglomerados),Não especial,True,None,None,NaN,NaN,NaN,NaN,False,1200302,880631.0,False,-99,Norte,1200302,NaN,False,NaN,False,Interior,Interior,False
3,AC_Acre_12,00049061283,ESTADO,CPF,30000.00,202505,202505,2025,2025,10 a 50 mil,De 10 a 50 mil,AC,12,Acre,N,Feminino,N,Microempreendedor individual (MEI),Outras ocupações não especificadas anteriormente,35.0,25-54 anos,1200401,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,422105,RECEPCIONISTA EM GERAL,False,True,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,None,None,NaN,NaN,NaN,NaN,False,1200401,880631.0,False,-99,Norte,1200401,NaN,False,1200401,True,Capital,Capital,True
4,AC_Acre_12,00335951279,ESTADO,CPF,30000.00,202502,202502,2025,2025,10 a 50 mil,De 10 a 50 mil,AC,12,Acre,N,Masculino,N,NaN,NaN,37.0,25-54 anos,1200450,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,Preta/negra – para a pessoa que se enquadrar c...,Ensino Médio completo.,Médio completo e superior incompleto,0,NaN,0,Trabalhador urbano vinculado a empregador pess...,Trabalhador urbano e aprendiz regidos pela CLT,517330,True,False,NÃO SE APLICA,True,517330,VIGILANTE,False,True,Rural,Área rural (exclusive aglomerados),Não especial,True,None,None,NaN,NaN,NaN,NaN,False,1200450,880631.0,False,-99,Norte,1200450,NaN,False,NaN,False,Interior,Interior,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166881,TO_Wanderlandia_1722081,48422732000104,MUNICIPIO,CNPJ,4670.26,202407,202407,2024,2024,2 a 10 mil,De 2 a 10 mil,TO,1722081,Wanderlandia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,False,"{'codigo': '7739003', 'descricao': 'Aluguel de...","[{'codigo': '7729202', 'descricao': 'Aluguel d...","{'codigo': '2135', 'descricao': 'Empresário (I...",01 - MicroEmpresa-ME,True,CNAE NAO CULTURAL,1702109,7739003,"Aluguel de palcos, coberturas e outras estrutu...",MEI,CNAE NAO EDUCACAO,CNAE NAO AUDIOVISUAL,True,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,<NA>,False,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,None,None,NaN,NaN,NaN,NaN,None,1702109,10751.0,False,1_pequeno_i,Norte,1722081,NaN,False,NaN,False,Interior,Interior,False
166882,TO_Wanderlandia_1722081,49084186168,MUNICIPIO,CPF,2700.00,202511,202511,2025,2025,2 a 10 mil,De 2 a 10 mil,TO,1722081,Wanderlandia,N,Feminino,N,Natureza da ocupação não especificada anterior...,Outras ocupações não especificadas anteriormente,61.0,55-64 anos,1722081,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,False,True,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,True,False,De dois salários-mínimos até três salários-mín...,Urbanas,Superior a um salário mínimo,Acima de 1/2 salário mínimo,False,1722081,10751.0,False,1_pequeno_i,Norte,1722081,NaN,False,NaN,False,Interior,Interior,False
166883,TO_Wanderlandia_1722081,70359391133,MUNICIPIO,CPF,3086.23,202412,202412,2024,2024,2 a 10 mil,De 2 a 10 mil,TO,1722081,Wanderlandia,N,Masculino,N,NaN,NaN,25.0,25-54 anos,1722081,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,False,True,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,True,True,De 0 a um salário-mínimo,Urbanas,"De R$ 109,01 até R$ 218",Pobreza,False,1722081,10751.0,False,1_pequeno_i,Norte,1722081,NaN,False,NaN,False,Interior,Interior,False
166884,TO_Wanderlandia_1722081,86692666104,MUNICIPIO,CPF,1794.12,202412,202412,2024,2024,Até 2 mil,Até 2 mil,TO,1722081,Wanderlandia,N,Feminino,N,Natureza da ocupação não especificada anterior...,Outras ocupações não especificadas anteriormente,50.0,25-54 anos,1722081,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,55215,"TRAB DE S GERAIS (SERVICOS CONSERVACAO, MANUT ...",False,True,Rural,Área rural (exclusive aglomerados),Não especial,True,None,None,NaN,NaN,NaN,NaN,False,1722081,10751.0,False,1_pequeno_i,Norte,1722081,NaN,False,NaN,False,Interior,Interior,False
166885,TO_Wanderlandia_1722081,88687481187,MUNICIPIO,CPF,1794.12,202412,202412,2024,2024,Até 2 mil,Até 2 mil,TO,1722081,Wanderlandia,N,Feminino,N,NaN,NaN,53.0,25-54 anos,1722081,True,NaN,NaN,NaN,NaN,None,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,None,<NA>,NÃO SE APLICA,False,<NA>,NaN,False,True,Urbana,Área urbana de alta densidade de edificações d...,Não especial,True,True,True,De 0 a um salário-mínimo,Urbanas,"De R$ 109,01 até R$ 218",Pobreza,False,1722081,10751.0,False,1_pequeno_i,Norte,1722081,NaN,False,NaN,False,Interior,Interior,False

In [ ]:
df_box_qtd_contemplados = df_box[df_box['metrica'] == 'valor_t1ransacao_total_bbagil']
df_box_qtd_contemplados.to_csv(settings.DATA_PATH_SECTION2 / 'faixa_valor_box_plot_valor_transacao_total_bbagil_state.csv')

# Section 3

In [16]:
importlib.reload(person)

In [7]:
# aggregate_contemplados_pf_pj_proportion.csv
df_person = person.aggregate_contemplados_pf_pj_proportion(df_cubo=df_cubo)
df_person.to_csv(settings.DATA_PATH_SECTION3 / 'aggregate_contemplados_pf_pj_proportion.csv')

In [11]:
df_cubo['tipo_documento'].value_counts(dropna=False)

tipo_documento
CPF     130235
CNPJ     25363
Name: count, dtype: int64

In [8]:
# aggregate_contemplados_by_sexo_proportion.csv
df_sexo = person.aggregate_contemplados_by_sexo_proportion(df_cubo=df_cubo)
df_sexo.to_csv(settings.DATA_PATH_SECTION3 / 'aggregate_contemplados_by_sexo_proportion.csv')

In [50]:
df_sexo.head(2)

,quantidade_contemplados,perc_quantidade_contemplados,valor_contemplados,perc_valor_contemplados,quantidade_contemplados_feminino,perc_quantidade_contemplados_feminino,valor_contemplados_feminino,perc_valor_contemplados_feminino,quantidade_contemplados_masculino,perc_quantidade_contemplados_masculino,valor_contemplados_masculino,perc_valor_contemplados_masculino
0,134593,1,1254423238,1,62943,0.467654,578195818,0.460926,71650,0.532346,676227421,0.539074

In [13]:
# aggregate_valor_quantity_by_age_group_sexo_wide
df_age_group = person.aggregate_valor_quantity_by_age_group_sexo_wide(df_cubo=df_cubo)
df_age_group.to_csv(settings.DATA_PATH_SECTION3 / 'aggregate_valor_quantity_by_age_group_sexo_wide.csv')

In [ ]:
# aggregate_value_quantity_by_age_group_region_wide
df_age_region = person.aggregate_value_quantity_by_age_group_region_wide(df_cubo=df_cubo)
df_age_region.to_csv(settings.DATA_PATH_SECTION3 / 'aggregate_value_quantity_by_age_group_region_wide.csv')

# Section 4

In [43]:
importlib.reload(labor)

In [41]:
# aggregate_vinculo_formal_labor.csv
df_not_in_mercado = labor.aggregate_vinculo_formal_labor(df_cubo=df_cubo)
df_not_in_mercado.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor.csv')

In [42]:
# aggregate_vinculo_formal_labor_by_uf.csv
df_not_in_mercado_by_uf = labor.aggregate_vinculo_formal_labor_by_uf(df_cubo=df_cubo)
df_not_in_mercado_by_uf.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_uf.csv')

In [43]:
# aggregate_vinculo_formal_labor_by_region.csv
df_not_in_mercado_by_region = labor.aggregate_vinculo_formal_labor_by_region(df_cubo=df_cubo)
df_not_in_mercado_by_region.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_region.csv')

In [46]:
# aggregate_vinculo_formal_labor_by_sexo.csv
df_not_in_mercado_by_sexo = labor.aggregate_vinculo_formal_labor_by_sexo(df_cubo=df_cubo)
df_not_in_mercado_by_sexo.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_sexo.csv')

In [50]:
# aggregate_vinculo_formal_labor_by_age_group.csv
df_not_in_mercado_by_age_group = labor.aggregate_vinculo_formal_labor_by_age_group(df_cubo=df_cubo)
df_not_in_mercado_by_age_group.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_age_group.csv')

In [56]:
# aggregate_vinculo_formal_labor_by_raca_cor.csv
df_not_in_mercado_by_raca_cor = labor.aggregate_vinculo_formal_labor_by_raca_cor(df_cubo=df_cubo)
df_not_in_mercado_by_raca_cor.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_raca_cor.csv')

In [ ]:
# aggregate_raca_cor_vinculo_formal_labor_by_sexo
df_not_in_mercado_by_raca_cor_sexo = labor.aggregate_raca_cor_vinculo_formal_labor_by_sexo(df_cubo=df_cubo)
df_not_in_mercado_by_raca_cor_sexo.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_raca_cor_vinculo_formal_labor_by_sexo.csv')

In [67]:
# aggregate_vinculo_formal_labor_by_escolaridade.csv
df_not_in_mercado_escolaridade = labor.aggregate_vinculo_formal_labor_by_escolaridade(df_cubo=df_cubo)
df_not_in_mercado_escolaridade.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_formal_labor_by_escolaridade.csv')

In [69]:
# aggregate_vinculo_trabalho_formal_by_escolaridade_clean.csv
df_not_in_mercado_escolaridade_clean = labor.aggregate_vinculo_trabalho_formal_by_escolaridade_sem_sem_informacao(df_cubo=df_cubo)
df_not_in_mercado_escolaridade_clean.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_vinculo_trabalho_formal_by_escolaridade_clean.csv')

In [ ]:
# CBOS

np.float64(12415168.75)

In [46]:
# aggregate_cbo_rais.csv
df_cbo_rais = labor.aggregate_cbo_rais(df_cubo=df_cubo)
df_cbo_rais.to_csv(settings.DATA_PATH_SECTION4 / 'aggregate_cbo_rais.csv')

In [1]:
df_cubo

NameError: name 'df_cubo' is not defined

# Section 5

In [177]:
importlib.reload(cadunico)

In [47]:
df_cad_unico = pd.read_parquet(settings.DATA_PATH / 'input_data' / 'non-public' /'dim_cadunico__2026-05-19_18-17.parquet')

In [100]:
# aggregate_cadunico_summary.csv
df_cubo_cadunico = cadunico.aggregate_cadunico_summary(df_cubo=df_cubo)
df_cubo_cadunico.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_summary.csv')

In [101]:
# aggregate_cadunico_profile_summary.csv
df_cubo_cadunico_sexo_idade = cadunico.aggregate_cadunico_profile_summary(df_cubo=df_cubo)
sexo = df_cubo_cadunico_sexo_idade[df_cubo_cadunico_sexo_idade['dimensao'] == 'Sexo']
faixa_etaria = df_cubo_cadunico_sexo_idade[df_cubo_cadunico_sexo_idade['dimensao'] == 'Faixa etária']
sexo.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_profile_summary_by_sexo.csv')
faixa_etaria.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_profile_summary_by_faixa_etaria.csv')

In [ ]:
# aggregate_cadunico_faixa_etaria_by_sexo.csv
df_cubo_cadunico_sexo_idade_juntos = cadunico.aggregate_cadunico_faixa_etaria_by_sexo(df_cubo=df_cubo)
df_cubo_cadunico_sexo_idade_juntos.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_faixa_etaria_by_sexo.csv')

In [ ]:
# aggregate_cadunico_by_situacao_renda.csv
df_cad_unico_situacao_renda = cadunico.aggregate_cadunico_by_situacao_renda(df_cubo=df_cubo)
df_cad_unico_situacao_renda.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_situacao_renda.csv')

In [ ]:
# aggregate_cadunico_by_fx_renda_per_capita.csv
df_cad_unico_situacao_faixa_renda_percapita = cadunico.aggregate_cadunico_by_fx_renda_per_capita(df_cubo=df_cubo)
df_cad_unico_situacao_faixa_renda_percapita.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_fx_renda_per_capita.csv')

In [ ]:
# aggregate_cadunico_by_situacao_domicilio.csv
df_cad_unico_domicilio_situacao = cadunico.aggregate_cadunico_by_situacao_domicilio(df_cubo=df_cubo)
df_cad_unico_domicilio_situacao.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_situacao_domicilio.csv')

In [187]:
# aggregate_cadunico_by_population_size.csv
df_cad_unico_porte_populacional = cadunico.aggregate_cadunico_by_population_size(df_cubo=df_cubo)
df_cad_unico_porte_populacional.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_population_size.csv')

In [188]:
# aggregate_cadunico_by_uf.csv
df_cad_unico_by_uf = cadunico.aggregate_cadunico_by_uf(df_cubo=df_cubo)
df_cad_unico_by_uf.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_uf.csv')

In [172]:
# aggregate_cadunico_by_value_group.csv
df_cad_unic_faixa_valor = cadunico.aggregate_cadunico_by_value_group(df_cubo=df_cubo)
df_cad_unic_faixa_valor.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_cadunico_by_value_group.csv')

In [173]:
# aggregate_bolsa_familia_summary.csv
df_cad_unico_bpf = cadunico.aggregate_bolsa_familia_summary(df_cubo=df_cubo)
df_cad_unico_bpf.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_bolsa_familia_summary.csv')

In [180]:
# aggregate_bpc_summary.csv
df_cad_unico_bpc = cadunico.aggregate_bpc_summary(df_cubo=df_cubo)
df_cad_unico_bpc.to_csv(settings.DATA_PATH_SECTION5 / 'aggregate_bpc_summary.csv')

In [181]:
df_cpf_receita = pd.read_parquet(settings.DATA_PATH / 'input_data' / 'non-public' /'dim_cpf_receita__2026_05-19-13_09.parquet')

In [183]:
df_cpf_receita[df_cpf_receita['sexo_receita_cpf'] == 'Feminino']['cpf_receita_cpf'].nunique()

61026

In [184]:
df_cpf_receita[df_cpf_receita['sexo_receita_cpf'] == 'Masculino']['cpf_receita_cpf'].nunique()

68615

In [186]:
61026/(61026+68615)

0.47073071019199175